spring:
  application:
    name: ms-category
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: myuser
    password: mypassword
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/db.changelog-master.yml
    default-schema: public
    drop-first: false




